### ISSUE TITLE
Review comments for initial CTV draft

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse_task-view#2]
Some minor updates spotted needed:
- add sdtmchecks under SDTM
- admiraloptha typo should be admiralophtha
- add teal under TLG frameworks
- add envsetup and datasetjson under utility
- valtools is repeated and 2nd one should be riskmetric
- add covtracer and riskassessment under package validation

Looks really good though and i like the way you laid it all out!

**Comment by mstackhouse** [comment]
@rossfarrugia we can't include packages that aren't currently on CRAN. So I think we currently that sdtmchecks, teal, envsetup, and then I don't think covtracer and riskassessment would be things we can list there either.

**Comment by rossfarrugia** [comment]
ah yes of course! sorry you did say and of course makes sense with this being a "**CRAN** task view" after all. how about a general sentence somewhere to say we also have further resources available outside of CRAN - see pharmaverse.org. if CRAN would allow that.

**Comment by mstackhouse** [comment]
Ok I think I pushed fixes for all those issues (minux non-CRAN stuff). And the link out to pharmaverse site.

**Comment by rossfarrugia** [comment]
looks good, thanks!
